### PR TITLE
I added doc strings to 3 files

### PR DESCRIPTION
**Pull request by markdicks**
There were 3 files that I added doc strings for improved code readability and maintainability.

### CODE REVIEW

**Comment by markdicks** [comment]
I would love to work on more files and add more doc strings if you keen, just comment and let me know

**Comment by cloudwebrtc** [comment]
Yes, I'd love to accept PRs for these awesome docs, please go ahead.

**Review by cloudwebrtc — APPROVED** [review]

**Comment by markdicks** [comment]
Awesome thank you

**Comment by markdicks** [comment]
My bad I closed it thinking it was merged, apologies

**Comment by cloudwebrtc** [comment]
I can merge now, but if you want to continue adding for other files, I will review later

**Comment by markdicks** [comment]
In about 10-12 hours I will be back to continue with the rest of the files in the libwebrtc/src folder. Hopefully finish those, for now you can merge if you comfortable with that.

**Comment by markdicks** [comment]
Then do lemme know which files you'd like me to focus on then I will do those as well.

**Comment by cloudwebrtc** [comment]
In terms of priority, the API documentation in `libwebrtc/include` is the most needed to add docs, you can start here If you want, most APIs can refer to https://developer.mozilla.org/en-US/docs/Web /API/WebRTC_API is the calling method,

**Comment by markdicks** [comment]
The two deletions are coming from the 'include/rtc_audio_device.h' file, there were two comments that I removed, about 4 words each. I removed them because it seemed covered in the new doc strings I added in both deletions. Hope you don't mind that minor change. Your code still remains unaffected. 

On that I have done 4 files in the folder you suggested and went in depth for all four. I hope to continue later on today, you can merge as this is the first load of doc strings. I hope to do 4 big batches like this. Hope you are satisfied. Talk soon xD

**Comment by cloudwebrtc** [comment]
lgtm!

**Comment by markdicks** [comment]
Okay will do from now on, thank you

**Comment by markdicks** [comment]
Okay will do from now on, thank you

**Comment by markdicks** [comment]
Good day, hope you doing well today. Sorry for my lack of knowledge, I am not sure what is meant when you say create a PR in the branch. Please do let me know, and then furthermore I did not make any changes to the master branch on my side after you merged but it still tells me that I am 9 commits ahead. Sorry about this, I tried asking a work colleague about it but even they was not sure what to do.

**Pull request merged**
