### PR TITLE
Support Screen capture

### PR DESCRIPTION
**Pull request by dkubrakov**

### CODE REVIEW

**Comment by dkubrakov** [comment]
Working example flutter-webrtc: 
https://github.com/dkubrakov/flutter-webrtc/tree/feat/screen-capture

**Comment by cloudwebrtc** [comment]
hey @dkubrakov,  that‘s awesome

> Working example flutter-webrtc:
https://github.com/dkubrakov/flutter-webrtc/tree/feat/screen-capture

I tested this branch and it works, I want to return the thumbnail in Source, the underlying processing should be after getting the source list, apply to get a frame RTCVideoFrame for each source, and then get to the thumbnail.

I'm implementing DesktopCapture for macOS on another branch, https://github.com/webrtc-sdk/webrtc/blob/feat/support-screen-capture-for-mac/sdk/objc/components/capturer/RTCDesktopCapturer.h

I think we can synchronize a bit, keep consistency at the dart level, and complete this feature.
Any idea can be discussed

**Comment by dkubrakov** [comment]
At the moment, that's all. 
After a while I will be able to return to this task (return the thumbnail in Source). 
As an interface, I was targeting https://github.com/flutter-webrtc/flutter-webrtc/issues/799.

https://github.com/dkubrakov/webrtc-interface/blob/feat/desktop-cpaturer/lib/src/desktop_capturer.dart
https://github.com/dkubrakov/flutter-webrtc/tree/feat/screen-capture
https://github.com/dkubrakov/libwebrtc/tree/feat/screen-capture

**Comment by dkubrakov** [comment]
Updated the release of screen capture, taking into account the upgrade to m97.
What prevents (still needs to be done) to add this feature?
* There is a small difference in libvwebrtc (class RTCDesktopCapturer), how critical it is...

https://github.com/dkubrakov/libwebrtc/tree/feat/screen-capture
https://github.com/dkubrakov/flutter-webrtc/tree/feat/screen-capture
https://github.com/dkubrakov/webrtc-interface/tree/feat/desktop-cpaturer

**Comment by cloudwebrtc** [comment]
@dkubrakov great work,  I think we can merge after syncing both PRs, here I have some new changes.

1, I moved `webrtc_interface/lib/src/desktop_capturer.dart` to `flutter_webrtc/lib/src/desktop_capturer.dart`, because `dart_webrtc` uses `getDisplayMedia `to pop up screen/window selection dialog via `browser api`.  so `desktopCapture` is dedicated to desktop.

here is the PR for macOS.
https://github.com/flutter-webrtc/flutter-webrtc/pull/940/files

So we need to merge these two files.
* [desktopcapturer_impl.dart@dkubrakov](https://github.com/dkubrakov/flutter-webrtc/blob/feat/screen-capture/lib/src/native/desktopcapturer_impl.dart)
* [desktop_capturer_impl.dart@cloudwebrtc](https://github.com/flutter-webrtc/flutter-webrtc/blob/feat/screen-capture-for-mac/lib/src/native/desktop_capturer_impl.dart)

2, I implemented full screen/window capture in macOS and supports thumbnail export, so I think you can refer to this code to generate thumbnails for windows part. (use libjpeg)

https://github.com/webrtc-sdk/webrtc/pull/24/files

[objc_desktop_capture.h](https://github.com/webrtc-sdk/webrtc/blob/feat/support-screen-capture-for-mac/sdk/objc/native/src/objc_desktop_capture.h)
[objc_desktop_capture.mm](https://github.com/webrtc-sdk/webrtc/blob/feat/support-screen-capture-for-mac/sdk/objc/native/src/objc_desktop_capture.mm)
[objc_desktop_media_list.h](https://github.com/webrtc-sdk/webrtc/blob/feat/support-screen-capture-for-mac/sdk/objc/native/src/objc_desktop_media_list.h)
[objc_desktop_media_list.mm](https://github.com/webrtc-sdk/webrtc/blob/feat/support-screen-capture-for-mac/sdk/objc/native/src/objc_desktop_media_list.mm)

BTW, If you need more timely discussion, you can add my Telegram ID. https://t.me/cloudwebrtc

**Comment by cloudwebrtc** [comment]
hey @dkubrakov, looks great, can you create a new PR for flutter-webrtc? I think we will be able to merge soon

> I did the thumbnail generation at the plugin level. This is much less expensive than implementing the DesktopMediaList, DesktopMediaList::MediaSource interface.

At present, it is indeed possible to make consistent calls between windows and mac.

My intention to create thumbnails with `libjpeg` is for the upcoming `flutter linux` version, so we can make the linux version achieve exactly the same screen-sharing functionality with almost no code changes,

I have committed the relevant common code to this branch
https://github.com/webrtc-sdk/libwebrtc/compare/feat/desktop-capture

would you mind merging this code into your branch to continue working on your PR? I guess this can reduce some workload.

**Comment by cloudwebrtc** [comment]
Or you can create a flutter-webrtc PR first, I will merge it after the test is ok They also include this PR, then I will replace the libwebrtc part of the code with my PR, it will be a perfect feature for us to work together.

**Pull request merged**
